#!/usr/bin/env bash

python_setup_dir=$(git rev-parse --show-toplevel)/python_setup_dir
python_setup_files=$(find "$python_setup_dir" -maxdepth 1 -type f -name "*")

for python_setup_file in $python_setup_files; do
  ln -sf "$python_setup_file" . 2>/dev/null
done

vscode_dir=$(find "$python_setup_dir" -maxdepth 1 -type d -name ".vscode")
if [ -d "$vscode_dir" ]; then
  ln -sf "$vscode_dir" . 2>/dev/null
fi

touch ".root" 2>/dev/null
